### PR TITLE
Make get-hash public

### PR DESCRIPTION
**Pull request by pcarlisle**

### CODE REVIEW

**Comment by briancain** [comment]
Makes sense to me 👍

**Comment by smcclellan** [comment]
You should be able to remove the `(def get-hash #'puppetlabs.dujour.version-check/get-hash)` workaround after this.

**Comment by pcarlisle** [comment]
oh is that in the tests, i'll do that

**Comment by smcclellan** [comment]
That should fix Travis.

**Comment by pcarlisle** [comment]
This is lazy, I'm going to do something less lazy.

**Comment by pcarlisle** [comment]
this turned out to be sufficient after all

**Comment by smcclellan** [comment]
Remove the failing line from the unit test then?

**Comment by pcarlisle** [comment]
I did

**Comment by smcclellan** [comment]
I see it now, 👍 to merge.

**Pull request merged**
